AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - "Rakefile"
    - "config.ru"

Style/Documentation:
  Enabled: false
