version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: historica_postgres_container
    environment:
      POSTGRES_DB: historica_development
      POSTGRES_USER: historica
      POSTGRES_PASSWORD: historica
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - historica_network

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - historica_network

volumes:
  postgres_data:
  redis_data:

networks:
  historica_network:
