version: '3.8'

services:
#  api:
#    build: .
#    command: bundle exec rails server -b 0.0.0.0
#    volumes:
#      - .:/app
#      - gem_cache:/usr/local/bundle
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
#      - redis
#      - meilisearch
#    environment:
#      RAILS_ENV: development
#      DB_HOST: postgres
#      MEILISEARCH_HOST: http://meilisearch:7700
#      SIDEKIQ_SERVER: redis://redis:6379/0
#      SIDEKIQ_CLIENT: redis://redis:6379/0
#    networks:
#      - historica_network

  postgres:
    image: postgres:16.0-alpine
    container_name: historica_postgres_container
    environment:
      POSTGRES_DB: historica_development
      POSTGRES_USER: historica
      POSTGRES_PASSWORD: historica
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - historica_network

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - historica_network

  meilisearch:
    image: getmeili/meilisearch:v1.5
    ports:
      - "7700:7700"
    networks:
      - historica_network
    environment:
      MEILI_NO_ANALYTICS: "true"

volumes:
  postgres_data:
  redis_data:
  gem_cache:

networks:
  historica_network:
